version: "3.7"
services:
  db:
    #image: arm64v8/mysql:5.7.23
    image: arm64v8/mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./sql/codepush-all.sql:/docker-entrypoint-initdb.d/codepush-all.sql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "On"
  redis:
    image: arm64v8/redis:4.0.11-alpine
    volumes:
      - ./data/redis:/data
    ports:
      - "6388:6379"
